ALTER TABLE
    `order_shipment` MODIFY COLUMN `id` VARCHAR(36) NOT NULL DEFAULT (UUID());

ALTER TABLE
    `order` MODIFY COLUMN `id` VARCHAR(36) NOT NULL DEFAULT (UUID());

ALTER TABLE
    `order_item` MODIFY COLUMN `id` VARCHAR(36) NOT NULL DEFAULT (UUID());