server:
  port: 8080

logging:
  pattern:
    console: "%green(%d{HH:mm:ss}) %yellow([%t]) %blue(%-5level) %magenta(%logger{36}) - %msg%n"
  level:
    org.springframework.web: DEBUG

spring:
  banner:
    location: classpath:banner.txt
  application:
    name: mssc-pirate-parrot-gateway
  threads:
    virtual:
      enabled: true

  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "https://pp-admin-fd160.web.app"
            allowedMethods: "GET, POST, PUT, DELETE, OPTIONS"
            allowedHeaders: "*"
            allowCredentials: true
        add-to-simple-url-handler-mapping: true
      routes:
        - id: verify
          uri: http://verify:8081
          predicates:
            - Path=/api/v1/verify/**
        - id: product
          uri: http://product:8082
          predicates:
            - Path=/api/v1/product/**
        - id: order
          uri: http://order:8083
          predicates:
            - Path=/api/v1/order/**
        - id: communication
          uri: http://communication:8084
          predicates:
            - Path=/api/v1/communication/**

