
DROP TABLE IF EXISTS `authorizations`;
create table `authorizations` (
                                  `id` VARCHAR(36) NOT NULL,
                                  `registered_client_id` varchar(36) NOT NULL,
                                  `principal_name` varchar(256) NOT NULL,
                                  `authorization_grant_type` varchar(64) NOT NULL,
                                  `authorized_scopes` varchar(256) NOT NULL,
                                  `attributes` TEXT NOT NULL,
                                  `state` varchar(256),
                                  `authorization_code_value` varchar(512),
                                  `authorization_code_issued_at` timestamp,
                                  `authorization_code_expires_at` timestamp,
                                  `authorization_code_metadata` TEXT,
                                  `access_token_value` varchar(1024),
                                  `access_token_issued_at` timestamp,
                                  `access_token_expires_at` timestamp,
                                  `access_token_metadata` TEXT NOT NULL,
                                  `access_token_type` varchar(32),
                                  `access_token_scopes` varchar(256),
                                  `refresh_token_value` varchar(1024) NOT NULL,
                                  `refresh_token_issued_at` timestamp,
                                  `refresh_token_expires_at` timestamp,
                                  `refresh_token_metadata` TEXT,
                                  `oidc_id_token_value` varchar(1024),
                                  `oidc_id_token_issued_at` timestamp,
                                  `oidc_id_token_expires_at` timestamp,
                                  `oidc_id_token_metadata` TEXT,
                                  `oidc_id_token_claims` TEXT,
                                  `user_code_value` varchar(64),
                                  `device_code_value` varchar(64),
                                  `device_code_issued_at` timestamp,
                                  `device_code_expires_at` timestamp,
                                  `device_code_metadata` TEXT,
                                  FOREIGN KEY (registered_client_id) REFERENCES registered_clients(id),
                                  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;