server:
  port: 9000

logging:
  pattern:
    console: "%green(%d{HH:mm:ss}) %yellow([%t]) %blue(%-5level) %magenta(%logger{36}) - %msg%n"
  level:
    org.springframework.web: TRACE

spring:
  banner:
    location: classpath:banner.txt
  application:
    name: mssc-pirate-parrot-authorization
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url:  jdbc:mysql://127.0.0.1:3306/pirate_parrot_authorization_db?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: root
    password: password
  threads:
    virtual:
      enabled: true
  data:
    redis:
      host: localhost
      port: 6379
      username:
      password:
  cache:
    type: redis
    redis:
      time-to-live: 60000


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: io.factorialsystems.msscpirateparrotauthorization.repository

pirate-parrot:
  config:
    allowed-origins:
      - http://localhost:4200
      - http://localhost:8080

